### ISSUE TITLE
What is the status of this project

### ISSUE THREAD

**Issue by TRex22** [murray1978/emu86#1]
This seems to be an interesting idea ... but the uno is 8bit whilst the 8086 is 16bit. 

Ive been thinking how to solve this:
The ATMEGA can run more than double the clock rate of the old 8086 so you could try some kind of multiplexing and use a faster clock speed to make up the second half of the bus or run two atmegas and sync them to the same clock with a bus running between them I2C probably wont work well enough and a custom thing would have to be cobbled together.

**Comment by Muzzdeni** [comment]
I haven't looked at the code for at least two years.
At least I have documented most of the code, some of it I do wonder what was I thinking. 

I'm not worried by the fact that the ATMEGA is 8bit and the 8088/8086 is 16bit as we can emulate the 16bit side of thing's as I am not connecting to real hardware, yet.

I may have been at the point where I needed the memory to be in an I2C eprom (24LC256) or testing the mov and jmp opcodes for when the CPU resets

**Comment by TRex22** [comment]
Yeah, I wanted to know how far you got ... Also if the code was safe. Im looking for a cool project to do since I have had it sit on my desk for far too long. Im thinking of installing HoodLoader2 which will allow me access to the other Atmega on the Uno and then using a bus run a emulation of x64 in parallel between the two processors. That would give the right sized bus.

**Comment by murray1978** [comment]
To all, not sure when I will be getting back to this one.
